### ISSUE TITLE
balance wrong property

### ISSUE THREAD

**Issue by alexeykarnachev** [nlsdfnbch/HFT-Orderbook#2]
It looks like a typo in lob.py (436:447). 

        if self.balance_factor > 1:
            # right is heavier
            if self.right_child.balance < 0:
                # right_child.left is heavier, RL case
                self._rl_case()
            elif self.right_child.balance > 0:
                # right_child.right is heavier, RR case
                self._rr_case()
        elif self.balance_factor < -1:
            # left is heavier
            if self.left_child.balance < 0:
                # left_child.left is heavier, LL case
                self._ll_case()
            elif self.left_child.balance > 0:
                # left_child.right is heavier, LR case
                self._lr_case()

Should be changed to

        if self.balance_factor > 1:
            # right is heavier
            if self.right_child.balance_factor < 0:
                # right_child.left is heavier, RL case
                self._rl_case()
            elif self.right_child.balance_factor > 0:
                # right_child.right is heavier, RR case
                self._rr_case()
        elif self.balance_factor < -1:
            # left is heavier
            if self.left_child.balance_factor < 0:
                # left_child.left is heavier, LL case
                self._ll_case()
            elif self.left_child.balance_factor > 0:
                # left_child.right is heavier, LR case
                self._lr_case()

Because there is no such property "balance", but only "balance_factor"

**Comment by nlsdfnbch** [comment]
You are correct. Thanks for reporting! I'll get on it right away.

**Comment by nlsdfnbch** [comment]
[Fixed](https://github.com/nlsdfnbch/HFT-Orderbook/commit/02d3856056b24cfce8dc23d8314f4b8ba310603d)
